name: "Alice"
colorset: 2
stack_frames: 4

# ---- NOVO: arma preferida ----
# Opções: Fist, Chainsaw, Pistol, Shotgun, SuperShotgun, Chaingun,
#         RocketLauncher, PlasmaRifle, BFG9000

# --- CONFIGURAÇÕES VISUAIS ---
render_settings:
  resolution: "RES_120X90"
  format: "GRAY8"
  hud: true

reward:
  engine:
    living_reward: 0.0
    frag_reward: 5.0
    hit_reward: 5.0
    hit_taken_reward: 0.0
    damage_made_reward: 5.0
    damage_taken_penalty: 0.0
    item_reward: 0.0
    health_reward: 0.0
    armor_reward: 0.0
    secret_reward: 0.0

  shaping:
    w_frag: 5.0
    w_health: 0.0
    w_armor: 0.0
    w_ammo2_cost: 0.00
    w_hits: 0.0
    w_hits_taken: 0.0
    w_deaths: 0.0
    step_penalty: -0.0001
    include_engine_reward: true  # still ignored by RewardShaper, OK

policy:
  algo: "ppo"
  extractor: "cnn_default"
  policy_kwargs:
    net_arch:
      pi: [256, 512, 512]
      vf: [512, 512, 256]

  learn_kwargs:
    n_steps: 256
    batch_size: 3072
    n_epochs: 4
    learning_rate_max: 6e-4
    learning_rate_min: 1e-7
    gamma: 0.99
    ent_coef: 0.05

model_dir: "models"
model_name: "alice_shared_ppo.zip"
train: true
train_steps: 6000000
