name: "stern_test_high_res"
colorset: 5
stack_frames: 4

render_settings:
  resolution: "RES_320X240"
  format: "GRAY8"
  hud: false

reward:
  engine:
    living_reward: 0.0
    frag_reward: 0.0
    hit_reward: 0.0
    hit_taken_reward: 0.0
    damage_made_reward: 0.0
    damage_taken_penalty: 0.0
    item_reward: 0.0
    health_reward: 0.0
    armor_reward: 0.0
    secret_reward: 0.0

  shaping:
    w_frag: 1.0
    w_health: 0.0
    w_armor: 0.0
    w_ammo2_cost: -0.01
    w_damage_made: 0.05
    w_hits: 0.0
    w_hits_taken: 0.0
    w_deaths: -5.0
    step_penalty: -0.002
    wall_stuck_penalty: -0.02
    include_engine_reward: false

  wall_stuck:
    min_move: 1.0
    max_turn_deg: 5.0
    persist_steps: 4

policy:
  algo: "ppo"
  extractor: "cnn_default"
  policy_kwargs:
    net_arch:
      pi: [256,256, 256]
      vf: [256,256, 256]

  learn_kwargs:
    n_steps: 512
    batch_size: 1024
    n_epochs: 16
    learning_rate_max: 3e-4
    learning_rate_min: 5e-5
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    vf_coef: 0.5
    ent_coef_max: 0.30
    ent_coef_min: 0.001

model_dir: "agents/deathmatch"
model_name: "stern_test_ppo.zip"
train: true
train_steps: 20000000
