name: "Pegador"
colorset: 1 # (Cor Vermelha)

engine_reward:
  # --- O OBJETIVO ---
  # Recompensa alta por "tocar" no fugitivo (dar dano com o soco)
  damage_made_reward: 10.0 
  
  # --- PENALIDADES ---
  # Não é penalizado por ser "tocado" de volta
  damage_taken_penalty: 0.0
  # Penalidade alta se acidentalmente matar o outro
  frag_reward: -100.0

shaping:
  w_deaths: -100.0
  # Sem penalidade de tempo. O objetivo é apenas caçar.
  step_penalty: 0.0
  include_engine_reward: true # Usa as recompensas acima

policy:
  algo: "ppo"
  policy_kwargs:
    # Reduzir a rede neural. Pega-Pega é simples, não precisa de 128 neurônios.
    net_arch:
      pi: [64, 64] # Era [128, 64]
      vf: [64, 64]
  learn_kwargs:
    n_steps: 128
    batch_size: 64
    
    learning_rate: 3e-4
    n_epochs: 3 # Quantas vezes ele repassa os dados. Menos epochs = treino mais rápido (mas talvez menos estável)

model_dir: "models"
model_name: "pegador_bot.zip"
train: true
train_steps: 750000