name: "Pegador"
colorset: 1 # Vermelho

engine_reward:
  # O OBJETIVO SUPREMO
  damage_made_reward: 10.0 
  
  # Se ele acertar um soco (hit), já dá um incentivo extra além do dano
  hit_reward: 1.0

  damage_taken_penalty: 0.0 # Ele é um tanque, não liga pra dor.
  
  # Matar é bom? No Pega-Pega sim, pois reinicia o round.
  # Mas cuidado: se frag_reward for muito alto, ele só foca em matar e não em "tocar".
  # Vamos deixar neutro ou levemente positivo, pois o damage_made já recompensa o toque.
  frag_reward: 5.0 

shaping:
  w_deaths: -10.0 # Se ele morrer (cair na lava/ácido), penalidade pequena.
  
  # --- A MUDANÇA MAIS IMPORTANTE ---
  # Penalidade por tempo. "Corra, você está perdendo pontos!"
  step_penalty: -0.01 
  include_engine_reward: true

policy:
  algo: "ppo"
  policy_kwargs:
    net_arch:
      pi: [256, 256, 256] # Cérebro Profundo para a Política (Ação)
      vf: [256, 256, 256] # Cérebro Profundo para o Valor (Estratégia)
  learn_kwargs:
    n_steps: 2048       # Planejamento de longo prazo (Padrão ouro do PPO)
    batch_size: 256     # Otimização massiva em blocos grandes
    learning_rate: 0.0001 # Passo de aprendizado menor para não "esquecer" o que aprendeu
    n_epochs: 4         # Atualizações eficientes sem over-fitting
    gamma: 0.995        # Foco brutal no futuro (O agente vai prever jogadas muito à frente)
    ent_coef: 0.01      # Curiosidade estável para explorar sem parecer bêbado

model_dir: "models"
model_name: "pegador_bot.zip"
train: true
train_steps: 15000000