name: "Fugitivo"
colorset: 8 # Verde

engine_reward:
  # Ganha pontos a cada instante que sobrevive. 
  # Isso ensina: "Fique longe de problemas".
  living_reward: 0.02 

  # --- PENALIDADES ---
  # Penalidade alta ao ser tocado. O objetivo supremo é evitar isso.
  damage_taken_penalty: -10.0
  
  # Penalidade por atacar: Isso "castra" o agente. 
  # Ele aprende que socar o pegador é desperdício de energia ou perigoso.
  damage_made_reward: -2.0 
  
  # Morrer é o pior cenário possível.
  frag_reward: -50.0 # Reduzi um pouco, pois -100 as vezes gera medo excessivo de explorar

shaping:
  w_deaths: -50.0
  step_penalty: 0.0 # Fugitivo não tem pressa, ele quer que o tempo passe.
  include_engine_reward: true

policy:
  algo: "ppo"
  policy_kwargs:
    net_arch:
      pi: [256, 256, 256] # Cérebro Profundo para a Política (Ação)
      vf: [256, 256, 256] # Cérebro Profundo para o Valor (Estratégia)
  learn_kwargs:
    n_steps: 2048       # Planejamento de longo prazo (Padrão ouro do PPO)
    batch_size: 256     # Otimização massiva em blocos grandes
    learning_rate: 0.0001 # Passo de aprendizado menor para não "esquecer" o que aprendeu
    n_epochs: 4         # Atualizações eficientes sem over-fitting
    gamma: 0.995        # Foco brutal no futuro (O agente vai prever jogadas muito à frente)
    ent_coef: 0.01      # Curiosidade estável para explorar sem parecer bêbado

model_dir: "models"
model_name: "fugitivo_bot.zip"
train: true
train_steps: 15000000 